# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlhM9TFSkyKF9MteSr9Ft9ScRtKT6mHR
"""

from itertools import product
import time
import matplotlib.pyplot  as plt


letras = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
letrasmay = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
numeros = ["1","2","3","4","5","6","7","8","9"]
caracteres = [".","; ",",","!","$","#","%","&","/","(",")","=","?","¿"]
almacen=[]
inte=[]

alfabeto = letras + letrasmay + numeros + caracteres
intentos = 0
encontrada = None

tiempo_inicio = time.perf_counter()

respeto="s"
respeto= input("desea ingresar mas datos s/n ")

while respeto == "s" or respeto=="S":
  contr = input("Ingrese una contraseña de prueba: ")
  for ch in contr:
      if ch not in alfabeto:
          print("El carácter",ch," no está en el alfabeto definido. Agrega ese carácter al alfabeto o cambia la contraseña.")
  for longitud in range(1, len(contr) + 1):
      for combo in product(alfabeto, repeat=longitud):
          intentos += 1
          intento = "".join(combo)

          if intento == contr:
            encontrada = intento
            print("Contraseña encontrada")
            print("Contraseña", encontrada)

            print("Intentos", intentos)
            inte.append(intentos)
            tiempo_fin = time.perf_counter()
            tiempo_transcurrido = tiempo_fin - tiempo_inicio
            print(tiempo_transcurrido)
            almacen.append(tiempo_transcurrido)
            respeto= input("desea ingresar mas datos s/n ")

  if not encontrada :
    print("No se encontró la contraseña.")
    print("Intentos ", intentos)
    print(tiempo_transcurrido)
    respeto= input("desea ingresar mas datos s/n ")


print(almacen)
print(inte)
plt.plot(almacen,inte)
plt.yscale("log")

plt.show